<?php

namespace Database\Seeders;

use App\Models\Clients\Country\City;
use App\Models\Clients\General\Status;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $status     =   Status::where('name', 'like', '%act%')->first()->id;

        $data[0]   = ['capital' => 0, 'status' => $status, 'estate' => 1, 'name' => ucfirst('General')];
        $data[1]   = ['capital' => 0, 'status' => $status, 'estate' => 1, 'name' => ucfirst('Maroa')];
        $data[2]   = ['capital' => 1, 'status' => $status, 'estate' => 1, 'name' => ucfirst('Puerto Ayacucho')];
        $data[3]   = ['capital' => 0, 'status' => $status, 'estate' => 1, 'name' => ucfirst('San Fernando de Atabapo')];

        $data[4]   = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('General')];
        $data[5]   = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('Anaco')];
        $data[6]   = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('Aragua de Barcelona')];
        $data[7]   = ['capital' => 1, 'status' => $status, 'estate' => 2, 'name' => ucfirst('Barcelona')];
        $data[8]   = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('Boca de Uchire')];
        $data[9]   = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('Cantaura')];
        $data[10]  = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('Clarines')];
        $data[11]  = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('El Chaparro')];
        $data[12]  = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('El Pao Anzoategui')];
        $data[13]  = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('El Tigre')];
        $data[14]  = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('El Tigrito')];
        $data[15]  = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('Guanape')];
        $data[16]  = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('Guanta')];
        $data[17]  = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('Lecheria')];
        $data[18]  = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('Onoto')];
        $data[19]  = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('Pariaguan')];
        $data[20]  = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('Piritu')];
        $data[21]  = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('Puerto La Cruz')];
        $data[22]  = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('Puerto Piritu')];
        $data[23]  = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('Sabana de Uchire')];
        $data[24]  = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('San Mateo Anzoategui')];
        $data[25]  = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('San Pablo Anzoategui')];
        $data[26]  = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('San Tome')];
        $data[27]  = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('Santa Ana de Anzoategui')];
        $data[28]  = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('Santa Fe Anzoategui')];
        $data[29]  = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('Santa Rosa')];
        $data[30]  = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('Soledad')];
        $data[31]  = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('Urica')];
        $data[32]  = ['capital' => 0, 'status' => $status, 'estate' => 2, 'name' => ucfirst('Valle de Guanape')];

        $data[33]  = ['capital' => 0, 'status' => $status, 'estate' => 3, 'name' => ucfirst('General')];
        $data[34]  = ['capital' => 0, 'status' => $status, 'estate' => 3, 'name' => ucfirst('Achaguas')];
        $data[35]  = ['capital' => 0, 'status' => $status, 'estate' => 3, 'name' => ucfirst('Biruaca')];
        $data[36]  = ['capital' => 0, 'status' => $status, 'estate' => 3, 'name' => ucfirst('Bruzual')];
        $data[37]  = ['capital' => 0, 'status' => $status, 'estate' => 3, 'name' => ucfirst('El Amparo')];
        $data[38]  = ['capital' => 0, 'status' => $status, 'estate' => 3, 'name' => ucfirst('El Nula')];
        $data[39]  = ['capital' => 0, 'status' => $status, 'estate' => 3, 'name' => ucfirst('Elorza')];
        $data[40]  = ['capital' => 0, 'status' => $status, 'estate' => 3, 'name' => ucfirst('Guasdualito')];
        $data[41]  = ['capital' => 0, 'status' => $status, 'estate' => 3, 'name' => ucfirst('Mantecal')];
        $data[42]  = ['capital' => 0, 'status' => $status, 'estate' => 3, 'name' => ucfirst('Puerto Paez')];
        $data[43]  = ['capital' => 1, 'status' => $status, 'estate' => 3, 'name' => ucfirst('San Fernando de Apure')];
        $data[44]  = ['capital' => 0, 'status' => $status, 'estate' => 3, 'name' => ucfirst('San Juan de Payara')];

        $data[45]  = ['capital' => 0, 'status' => $status, 'estate' => 4, 'name' => ucfirst('General')];
        $data[46]  = ['capital' => 0, 'status' => $status, 'estate' => 4, 'name' => ucfirst('Barbacoas')];
        $data[47]  = ['capital' => 0, 'status' => $status, 'estate' => 4, 'name' => ucfirst('Cagua')];
        $data[48]  = ['capital' => 0, 'status' => $status, 'estate' => 4, 'name' => ucfirst('Camatagua')];
        $data[49]  = ['capital' => 0, 'status' => $status, 'estate' => 4, 'name' => ucfirst('ChoronI')];
        $data[50]  = ['capital' => 0, 'status' => $status, 'estate' => 4, 'name' => ucfirst('Colonia Tovar')];
        $data[51]  = ['capital' => 0, 'status' => $status, 'estate' => 4, 'name' => ucfirst('El Consejo')];
        $data[52]  = ['capital' => 0, 'status' => $status, 'estate' => 4, 'name' => ucfirst('La Victoria')];
        $data[53]  = ['capital' => 0, 'status' => $status, 'estate' => 4, 'name' => ucfirst('Las Tejerias')];
        $data[54]  = ['capital' => 0, 'status' => $status, 'estate' => 4, 'name' => ucfirst('Magdaleno')];
        $data[55]  = ['capital' => 1, 'status' => $status, 'estate' => 4, 'name' => ucfirst('Maracay')];
        $data[56]  = ['capital' => 0, 'status' => $status, 'estate' => 4, 'name' => ucfirst('Ocumare de La Costa')];
        $data[57]  = ['capital' => 0, 'status' => $status, 'estate' => 4, 'name' => ucfirst('Palo Negro')];
        $data[58]  = ['capital' => 0, 'status' => $status, 'estate' => 4, 'name' => ucfirst('San Casimiro')];
        $data[59]  = ['capital' => 0, 'status' => $status, 'estate' => 4, 'name' => ucfirst('San Mateo')];
        $data[60]  = ['capital' => 0, 'status' => $status, 'estate' => 4, 'name' => ucfirst('San Sebastian')];
        $data[61]  = ['capital' => 0, 'status' => $status, 'estate' => 4, 'name' => ucfirst('Santa Cruz de Aragua')];
        $data[62]  = ['capital' => 0, 'status' => $status, 'estate' => 4, 'name' => ucfirst('TocorOn')];
        $data[63]  = ['capital' => 0, 'status' => $status, 'estate' => 4, 'name' => ucfirst('Turmero')];
        $data[64]  = ['capital' => 0, 'status' => $status, 'estate' => 4, 'name' => ucfirst('Villa de Cura')];
        $data[65]  = ['capital' => 0, 'status' => $status, 'estate' => 4, 'name' => ucfirst('Zuata')];
        
        $data[66]  = ['capital' => 0, 'status' => $status, 'estate' => 5, 'name' => ucfirst('General')];
        $data[67]  = ['capital' => 1, 'status' => $status, 'estate' => 5, 'name' => ucfirst('Barinas')];
        $data[68]  = ['capital' => 0, 'status' => $status, 'estate' => 5, 'name' => ucfirst('Barinitas')];
        $data[69]  = ['capital' => 0, 'status' => $status, 'estate' => 5, 'name' => ucfirst('Barrancas')];
        $data[70]  = ['capital' => 0, 'status' => $status, 'estate' => 5, 'name' => ucfirst('Calderas')];
        $data[71]  = ['capital' => 0, 'status' => $status, 'estate' => 5, 'name' => ucfirst('Capitanejo')];
        $data[72]  = ['capital' => 0, 'status' => $status, 'estate' => 5, 'name' => ucfirst('Ciudad Bolivia')];
        $data[73]  = ['capital' => 0, 'status' => $status, 'estate' => 5, 'name' => ucfirst('El CantOn')];
        $data[74]  = ['capital' => 0, 'status' => $status, 'estate' => 5, 'name' => ucfirst('Las Veguitas')];
        $data[75]  = ['capital' => 0, 'status' => $status, 'estate' => 5, 'name' => ucfirst('Libertad de Barinas')];
        $data[76]  = ['capital' => 0, 'status' => $status, 'estate' => 5, 'name' => ucfirst('Sabaneta')];
        $data[77]  = ['capital' => 0, 'status' => $status, 'estate' => 5, 'name' => ucfirst('Santa Barbara de Barinas')];
        $data[78]  = ['capital' => 0, 'status' => $status, 'estate' => 5, 'name' => ucfirst('SocopO')];
        
        $data[79]  = ['capital' => 0, 'status' => $status, 'estate' => 6, 'name' => ucfirst('General')];
        $data[80]  = ['capital' => 0, 'status' => $status, 'estate' => 6, 'name' => ucfirst('Caicara del Orinoco')];
        $data[81]  = ['capital' => 0, 'status' => $status, 'estate' => 6, 'name' => ucfirst('Canaima')];
        $data[82]  = ['capital' => 1, 'status' => $status, 'estate' => 6, 'name' => ucfirst('Ciudad Bolivar')];
        $data[83]  = ['capital' => 0, 'status' => $status, 'estate' => 6, 'name' => ucfirst('Ciudad Piar')];
        $data[84]  = ['capital' => 0, 'status' => $status, 'estate' => 6, 'name' => ucfirst('El Callao')];
        $data[85]  = ['capital' => 0, 'status' => $status, 'estate' => 6, 'name' => ucfirst('El Dorado')];
        $data[86]  = ['capital' => 0, 'status' => $status, 'estate' => 6, 'name' => ucfirst('El Manteco')];
        $data[87]  = ['capital' => 0, 'status' => $status, 'estate' => 6, 'name' => ucfirst('El Palmar')];
        $data[88]  = ['capital' => 0, 'status' => $status, 'estate' => 6, 'name' => ucfirst('El Pao')];
        $data[89]  = ['capital' => 0, 'status' => $status, 'estate' => 6, 'name' => ucfirst('Guasipati')];
        $data[90]  = ['capital' => 0, 'status' => $status, 'estate' => 6, 'name' => ucfirst('Guri')];
        $data[91]  = ['capital' => 0, 'status' => $status, 'estate' => 6, 'name' => ucfirst('La Paragua')];
        $data[92]  = ['capital' => 0, 'status' => $status, 'estate' => 6, 'name' => ucfirst('Matanzas')];
        $data[93]  = ['capital' => 0, 'status' => $status, 'estate' => 6, 'name' => ucfirst('Puerto Ordaz')];
        $data[94]  = ['capital' => 0, 'status' => $status, 'estate' => 6, 'name' => ucfirst('San Felix')];
        $data[95]  = ['capital' => 0, 'status' => $status, 'estate' => 6, 'name' => ucfirst('Santa Elena de Uairen')];
        $data[96]  = ['capital' => 0, 'status' => $status, 'estate' => 6, 'name' => ucfirst('Tumeremo')];
        $data[97]  = ['capital' => 0, 'status' => $status, 'estate' => 6, 'name' => ucfirst('Unare')];
        $data[98]  = ['capital' => 0, 'status' => $status, 'estate' => 6, 'name' => ucfirst('Upata')];

        $data[99]  = ['capital' => 0, 'status' => $status, 'estate' => 7, 'name' => ucfirst('General')];
        $data[100]  = ['capital' => 0, 'status' => $status, 'estate' => 7, 'name' => ucfirst('Bejuma')];
        $data[101]  = ['capital' => 0, 'status' => $status, 'estate' => 7, 'name' => ucfirst('Belen')];
        $data[102]  = ['capital' => 0, 'status' => $status, 'estate' => 7, 'name' => ucfirst('Campo de Carabobo')];
        $data[103]  = ['capital' => 0, 'status' => $status, 'estate' => 7, 'name' => ucfirst('Canoabo')];
        $data[104]  = ['capital' => 0, 'status' => $status, 'estate' => 7, 'name' => ucfirst('Central Tacarigua')];
        $data[105]  = ['capital' => 0, 'status' => $status, 'estate' => 7, 'name' => ucfirst('Chirgua')];
        $data[106]  = ['capital' => 0, 'status' => $status, 'estate' => 7, 'name' => ucfirst('Ciudad Alianza')];
        $data[107] = ['capital' => 0, 'status' => $status, 'estate' => 7, 'name' => ucfirst('El Palito')];
        $data[108] = ['capital' => 0, 'status' => $status, 'estate' => 7, 'name' => ucfirst('Guacara')];
        $data[109] = ['capital' => 0, 'status' => $status, 'estate' => 7, 'name' => ucfirst('Guigue')];
        $data[110] = ['capital' => 0, 'status' => $status, 'estate' => 7, 'name' => ucfirst('Las Trincheras')];
        $data[111] = ['capital' => 0, 'status' => $status, 'estate' => 7, 'name' => ucfirst('Los Guayos')];
        $data[112] = ['capital' => 0, 'status' => $status, 'estate' => 7, 'name' => ucfirst('Mariara')];
        $data[113] = ['capital' => 0, 'status' => $status, 'estate' => 7, 'name' => ucfirst('Miranda')];
        $data[114] = ['capital' => 0, 'status' => $status, 'estate' => 7, 'name' => ucfirst('Montalban')];
        $data[115] = ['capital' => 0, 'status' => $status, 'estate' => 7, 'name' => ucfirst('MorOn')];
        $data[116] = ['capital' => 0, 'status' => $status, 'estate' => 7, 'name' => ucfirst('Naguanagua')];
        $data[117] = ['capital' => 0, 'status' => $status, 'estate' => 7, 'name' => ucfirst('Puerto Cabello')];
        $data[118] = ['capital' => 0, 'status' => $status, 'estate' => 7, 'name' => ucfirst('San Joaquin')];
        $data[119] = ['capital' => 0, 'status' => $status, 'estate' => 7, 'name' => ucfirst('Tocuyito')];
        $data[120] = ['capital' => 0, 'status' => $status, 'estate' => 7, 'name' => ucfirst('Urama')];
        $data[121] = ['capital' => 1, 'status' => $status, 'estate' => 7, 'name' => ucfirst('Valencia')];
        $data[122] = ['capital' => 0, 'status' => $status, 'estate' => 7, 'name' => ucfirst('Vigirimita')];

        $data[123] = ['capital' => 0, 'status' => $status, 'estate' => 8, 'name' => ucfirst('General')];
        $data[124] = ['capital' => 0, 'status' => $status, 'estate' => 8, 'name' => ucfirst('Aguirre')];
        $data[125] = ['capital' => 0, 'status' => $status, 'estate' => 8, 'name' => ucfirst('Apartaderos Cojedes')];
        $data[126] = ['capital' => 0, 'status' => $status, 'estate' => 8, 'name' => ucfirst('Arismendi')];
        $data[127] = ['capital' => 0, 'status' => $status, 'estate' => 8, 'name' => ucfirst('Camuriquito')];
        $data[128] = ['capital' => 0, 'status' => $status, 'estate' => 8, 'name' => ucfirst('El Baul')];
        $data[129] = ['capital' => 0, 'status' => $status, 'estate' => 8, 'name' => ucfirst('El Limon')];
        $data[130] = ['capital' => 0, 'status' => $status, 'estate' => 8, 'name' => ucfirst('El Pao Cojedes')];
        $data[131] = ['capital' => 0, 'status' => $status, 'estate' => 8, 'name' => ucfirst('El Socorro')];
        $data[132] = ['capital' => 0, 'status' => $status, 'estate' => 8, 'name' => ucfirst('La Aguadita')];
        $data[133] = ['capital' => 0, 'status' => $status, 'estate' => 8, 'name' => ucfirst('Las Vegas')];
        $data[134] = ['capital' => 0, 'status' => $status, 'estate' => 8, 'name' => ucfirst('Libertad de Cojedes')];
        $data[135] = ['capital' => 0, 'status' => $status, 'estate' => 8, 'name' => ucfirst('Mapuey')];
        $data[136] = ['capital' => 0, 'status' => $status, 'estate' => 8, 'name' => ucfirst('Pinedo')];
        $data[137] = ['capital' => 0, 'status' => $status, 'estate' => 8, 'name' => ucfirst('Samancito')];
        $data[138] = ['capital' => 1, 'status' => $status, 'estate' => 8, 'name' => ucfirst('San Carlos')];
        $data[139] = ['capital' => 0, 'status' => $status, 'estate' => 8, 'name' => ucfirst('Sucre')];
        $data[140] = ['capital' => 0, 'status' => $status, 'estate' => 8, 'name' => ucfirst('Tinaco')];
        $data[141] = ['capital' => 0, 'status' => $status, 'estate' => 8, 'name' => ucfirst('Tinaquillo')];
        $data[142] = ['capital' => 0, 'status' => $status, 'estate' => 8, 'name' => ucfirst('Vallecito')];

        $data[143] = ['capital' => 1, 'status' => $status, 'estate' => 9, 'name' => ucfirst('General')];
        $data[144] = ['capital' => 1, 'status' => $status, 'estate' => 9, 'name' => ucfirst('Tucupita')];

        $data[145] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('General')];
        $data[146] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('Adicora')];
        $data[147] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('Boca de Aroa')];
        $data[148] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('Cabure')];
        $data[149] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('Capadare')];
        $data[150] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('Capatarida')];
        $data[151] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('Chichiriviche')];
        $data[152] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('Churuguara')];
        $data[153] = ['capital' => 1, 'status' => $status, 'estate' => 10, 'name' => ucfirst('Coro')];
        $data[154] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('Cumarebo')];
        $data[155] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('Dabajuro')];
        $data[156] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('Judibana')];
        $data[157] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('La Cruz de Taratara')];
        $data[158] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('La Vela de Coro')];
        $data[159] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('Los Taques')];
        $data[160] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('Maparari')];
        $data[161] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('Mene de Mauroa')];
        $data[162] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('Mirimire')];
        $data[162] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('Pedregal')];
        $data[163] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('Piritu FalcOn')];
        $data[164] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('Pueblo Nuevo FalcOn')];
        $data[165] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('Puerto Cumarebo')];
        $data[166] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('Punta CardOn')];
        $data[167] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('Punto Fijo')];
        $data[168] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('San Juan de Los Cayos')];
        $data[169] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('San Luis')];
        $data[170] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('Santa Ana FalcOn')];
        $data[171] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('Santa Cruz De Bucaral')];
        $data[172] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('Tocopero')];
        $data[173] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('Tocuyo de La Costa')];
        $data[174] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('Tucacas')];
        $data[175] = ['capital' => 0, 'status' => $status, 'estate' => 10, 'name' => ucfirst('Yaracal')];

        $data[176] = ['capital' => 0, 'status' => $status, 'estate' => 11, 'name' => ucfirst('General')];
        $data[177] = ['capital' => 0, 'status' => $status, 'estate' => 11, 'name' => ucfirst('Altagracia de Orituco')];
        $data[178] = ['capital' => 0, 'status' => $status, 'estate' => 11, 'name' => ucfirst('Cabruta')];
        $data[179] = ['capital' => 0, 'status' => $status, 'estate' => 11, 'name' => ucfirst('Calabozo')];
        $data[180] = ['capital' => 0, 'status' => $status, 'estate' => 11, 'name' => ucfirst('Camaguan')];
        $data[181] = ['capital' => 0, 'status' => $status, 'estate' => 11, 'name' => ucfirst('Chaguaramas Guarico')];
        $data[182] = ['capital' => 0, 'status' => $status, 'estate' => 11, 'name' => ucfirst('El Socorro')];
        $data[183] = ['capital' => 0, 'status' => $status, 'estate' => 11, 'name' => ucfirst('El Sombrero')];
        $data[184] = ['capital' => 0, 'status' => $status, 'estate' => 11, 'name' => ucfirst('Las Mercedes de Los Llanos')];
        $data[185] = ['capital' => 0, 'status' => $status, 'estate' => 11, 'name' => ucfirst('Lezama')];
        $data[186] = ['capital' => 0, 'status' => $status, 'estate' => 11, 'name' => ucfirst('Onoto')];
        $data[187] = ['capital' => 0, 'status' => $status, 'estate' => 11, 'name' => ucfirst('Ortiz')];
        $data[188] = ['capital' => 0, 'status' => $status, 'estate' => 11, 'name' => ucfirst('San Jose de Guaribe')];
        $data[189] = ['capital' => 1, 'status' => $status, 'estate' => 11, 'name' => ucfirst('San Juan de Los Morros')];
        $data[190] = ['capital' => 0, 'status' => $status, 'estate' => 11, 'name' => ucfirst('San Rafael de Laya')];
        $data[191] = ['capital' => 0, 'status' => $status, 'estate' => 11, 'name' => ucfirst('Santa Maria de Ipire')];
        $data[192] = ['capital' => 0, 'status' => $status, 'estate' => 11, 'name' => ucfirst('Tucupido')];
        $data[193] = ['capital' => 0, 'status' => $status, 'estate' => 11, 'name' => ucfirst('Valle de La Pascua')];
        $data[194] = ['capital' => 0, 'status' => $status, 'estate' => 11, 'name' => ucfirst('Zaraza')];

        $data[195] = ['capital' => 0, 'status' => $status, 'estate' => 12, 'name' => ucfirst('General')];
        $data[196] = ['capital' => 1, 'status' => $status, 'estate' => 12, 'name' => ucfirst('Barquisimeto')];
        $data[197] = ['capital' => 0, 'status' => $status, 'estate' => 12, 'name' => ucfirst('Atarigua')];
        $data[198] = ['capital' => 0, 'status' => $status, 'estate' => 12, 'name' => ucfirst('Aguada Grande')];
        $data[199] = ['capital' => 0, 'status' => $status, 'estate' => 12, 'name' => ucfirst('Bobare')];
        $data[200] = ['capital' => 0, 'status' => $status, 'estate' => 12, 'name' => ucfirst('Cabudare')];
        $data[201] = ['capital' => 0, 'status' => $status, 'estate' => 12, 'name' => ucfirst('Carora')];
        $data[202] = ['capital' => 0, 'status' => $status, 'estate' => 12, 'name' => ucfirst('Cubiro')];
        $data[203] = ['capital' => 0, 'status' => $status, 'estate' => 12, 'name' => ucfirst('Cuji')];
        $data[204] = ['capital' => 0, 'status' => $status, 'estate' => 12, 'name' => ucfirst('Duaca')];
        $data[205] = ['capital' => 0, 'status' => $status, 'estate' => 12, 'name' => ucfirst('El Manzano')];
        $data[206] = ['capital' => 0, 'status' => $status, 'estate' => 12, 'name' => ucfirst('El Tocuyo')];
        $data[207] = ['capital' => 0, 'status' => $status, 'estate' => 12, 'name' => ucfirst('Guarico')];
        $data[208] = ['capital' => 0, 'status' => $status, 'estate' => 12, 'name' => ucfirst('Humocaro Alto')];
        $data[209] = ['capital' => 0, 'status' => $status, 'estate' => 12, 'name' => ucfirst('Humocaro Bajo')];
        $data[210] = ['capital' => 0, 'status' => $status, 'estate' => 12, 'name' => ucfirst('La Miel')];
        $data[211] = ['capital' => 0, 'status' => $status, 'estate' => 12, 'name' => ucfirst('Moroturo')];
        $data[212] = ['capital' => 0, 'status' => $status, 'estate' => 12, 'name' => ucfirst('Quibor')];
        $data[213] = ['capital' => 0, 'status' => $status, 'estate' => 12, 'name' => ucfirst('Rio Claro')];
        $data[214] = ['capital' => 0, 'status' => $status, 'estate' => 12, 'name' => ucfirst('Sanare')];
        $data[215] = ['capital' => 0, 'status' => $status, 'estate' => 12, 'name' => ucfirst('Santa Ines')];
        $data[216] = ['capital' => 0, 'status' => $status, 'estate' => 12, 'name' => ucfirst('Sarare')];
        $data[217] = ['capital' => 0, 'status' => $status, 'estate' => 12, 'name' => ucfirst('Siquisique')];
        $data[218] = ['capital' => 0, 'status' => $status, 'estate' => 12, 'name' => ucfirst('Tintorero')];

        $data[219] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('General')];
        $data[220] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('Apartaderos Merida')];
        $data[221] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('Arapuey')];
        $data[222] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('Bailadores')];
        $data[223] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('Caja Seca')];
        $data[224] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('Canagua')];
        $data[225] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('Chachopo')];
        $data[226] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('Chiguara')];
        $data[227] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('Ejido')];
        $data[228] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('El Vigia')];
        $data[229] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('La Azulita')];
        $data[230] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('La Playa')];
        $data[231] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('Lagunillas Merida')];
        $data[232] = ['capital' => 1, 'status' => $status, 'estate' => 13, 'name' => ucfirst('Merida')];
        $data[233] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('Mesa de Bolivar')];
        $data[234] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('Mucuchies')];
        $data[235] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('Mucujepe')];
        $data[236] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('Mucuruba')];
        $data[237] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('Nueva Bolivia')];
        $data[238] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('Palmarito')];
        $data[239] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('Pueblo Llano')];
        $data[240] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('Santa Cruz de Mora')];
        $data[241] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('Santa Elena de Arenales')];
        $data[242] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('Santo Domingo')];
        $data[243] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('Tabay')];
        $data[244] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('Timotes')];
        $data[245] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('Torondoy')];
        $data[246] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('Tovar')];
        $data[247] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('Tucani')];
        $data[248] = ['capital' => 0, 'status' => $status, 'estate' => 13, 'name' => ucfirst('Zea')];

        $data[249] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('General')];
        $data[250] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('Araguita')];
        $data[251] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('Carrizal')];
        $data[252] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('Caucagua')];
        $data[253] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('Chaguaramas Miranda')];
        $data[254] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('Charallave')];
        $data[255] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('Chirimena')];
        $data[256] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('Chuspa')];
        $data[257] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('Cua')];
        $data[258] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('Cupira')];
        $data[259] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('Curiepe')];
        $data[260] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('El Guapo')];
        $data[261] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('El Jarillo')];
        $data[262] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('Filas de Mariche')];
        $data[263] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('Guarenas')];
        $data[264] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('Guatire')];
        $data[265] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('Higuerote')];
        $data[266] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('Los Anaucos')];
        $data[267] = ['capital' => 1, 'status' => $status, 'estate' => 14, 'name' => ucfirst('Los Teques')];
        $data[268] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('Ocumare del Tuy')];
        $data[269] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('Panaquire')];
        $data[270] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('Paracotos')];
        $data[271] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('Rio Chico')];
        $data[272] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('San Antonio de Los Altos')];
        $data[273] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('San Diego de Los Altos')];
        $data[274] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('San Fernando del Guapo')];
        $data[275] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('San Francisco de Yare')];
        $data[276] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('San Jose de Los Altos')];
        $data[277] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('San Jose de Rio Chico')];
        $data[278] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('San Pedro de Los Altos')];
        $data[279] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('Santa Lucia')];
        $data[280] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('Santa Teresa')];
        $data[281] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('Tacarigua de La Laguna')];
        $data[282] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('Tacarigua de Mamporal')];
        $data[283] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('Tacata')];
        $data[284] = ['capital' => 0, 'status' => $status, 'estate' => 14, 'name' => ucfirst('Turumo')];

        $data[285] = ['capital' => 0, 'status' => $status, 'estate' => 15, 'name' => ucfirst('General')];
        $data[286] = ['capital' => 0, 'status' => $status, 'estate' => 15, 'name' => ucfirst('Aguasay')];
        $data[287] = ['capital' => 0, 'status' => $status, 'estate' => 15, 'name' => ucfirst('Aragua de Maturin')];
        $data[288] = ['capital' => 0, 'status' => $status, 'estate' => 15, 'name' => ucfirst('Barrancas del Orinoco')];
        $data[289] = ['capital' => 0, 'status' => $status, 'estate' => 15, 'name' => ucfirst('Caicara de Maturin')];
        $data[290] = ['capital' => 0, 'status' => $status, 'estate' => 15, 'name' => ucfirst('Caripe')];
        $data[291] = ['capital' => 0, 'status' => $status, 'estate' => 15, 'name' => ucfirst('Caripito')];
        $data[292] = ['capital' => 0, 'status' => $status, 'estate' => 15, 'name' => ucfirst('Chaguaramal')];
        $data[293] = ['capital' => 0, 'status' => $status, 'estate' => 15, 'name' => ucfirst('Chaguaramas Monagas')];
        $data[294] = ['capital' => 0, 'status' => $status, 'estate' => 15, 'name' => ucfirst('El Furrial')];
        $data[295] = ['capital' => 0, 'status' => $status, 'estate' => 15, 'name' => ucfirst('El Tejero')];
        $data[296] = ['capital' => 0, 'status' => $status, 'estate' => 15, 'name' => ucfirst('Jusepin')];
        $data[297] = ['capital' => 0, 'status' => $status, 'estate' => 15, 'name' => ucfirst('La Toscana')];
        $data[298] = ['capital' => 1, 'status' => $status, 'estate' => 15, 'name' => ucfirst('Maturin')];
        $data[299] = ['capital' => 0, 'status' => $status, 'estate' => 15, 'name' => ucfirst('Miraflores')];
        $data[300] = ['capital' => 0, 'status' => $status, 'estate' => 15, 'name' => ucfirst('Punta de Mata')];
        $data[301] = ['capital' => 0, 'status' => $status, 'estate' => 15, 'name' => ucfirst('Quiriquire')];
        $data[302] = ['capital' => 0, 'status' => $status, 'estate' => 15, 'name' => ucfirst('San Antonio de Maturin')];
        $data[303] = ['capital' => 0, 'status' => $status, 'estate' => 15, 'name' => ucfirst('San Vicente Monagas')];
        $data[304] = ['capital' => 0, 'status' => $status, 'estate' => 15, 'name' => ucfirst('Santa Barbara')];
        $data[305] = ['capital' => 0, 'status' => $status, 'estate' => 15, 'name' => ucfirst('Temblador')];
        $data[306] = ['capital' => 0, 'status' => $status, 'estate' => 15, 'name' => ucfirst('Teresen')];
        $data[307] = ['capital' => 0, 'status' => $status, 'estate' => 15, 'name' => ucfirst('Uracoa')];

        $data[308] = ['capital' => 0, 'status' => $status, 'estate' => 16, 'name' => ucfirst('General')];
        $data[309] = ['capital' => 0, 'status' => $status, 'estate' => 16, 'name' => ucfirst('Altagracia')];
        $data[310] = ['capital' => 0, 'status' => $status, 'estate' => 16, 'name' => ucfirst('Boca de Pozo')];
        $data[311] = ['capital' => 0, 'status' => $status, 'estate' => 16, 'name' => ucfirst('Boca de Rio')];
        $data[312] = ['capital' => 0, 'status' => $status, 'estate' => 16, 'name' => ucfirst('El Espinal')];
        $data[313] = ['capital' => 0, 'status' => $status, 'estate' => 16, 'name' => ucfirst('El Valle del Espiritu Santo')];
        $data[314] = ['capital' => 0, 'status' => $status, 'estate' => 16, 'name' => ucfirst('El Yaque')];
        $data[315] = ['capital' => 0, 'status' => $status, 'estate' => 16, 'name' => ucfirst('Juangriego')];
        $data[316] = ['capital' => 1, 'status' => $status, 'estate' => 16, 'name' => ucfirst('La AsunciOn')];
        $data[317] = ['capital' => 0, 'status' => $status, 'estate' => 16, 'name' => ucfirst('La Guardia')];
        $data[318] = ['capital' => 0, 'status' => $status, 'estate' => 16, 'name' => ucfirst('Pampatar')];
        $data[319] = ['capital' => 0, 'status' => $status, 'estate' => 16, 'name' => ucfirst('Porlamar')];
        $data[320] = ['capital' => 0, 'status' => $status, 'estate' => 16, 'name' => ucfirst('Puerto Fermin')];
        $data[321] = ['capital' => 0, 'status' => $status, 'estate' => 16, 'name' => ucfirst('Punta de Piedras')];
        $data[322] = ['capital' => 0, 'status' => $status, 'estate' => 16, 'name' => ucfirst('San Francisco de Macanao')];
        $data[323] = ['capital' => 0, 'status' => $status, 'estate' => 16, 'name' => ucfirst('San Juan Bautista')];
        $data[324] = ['capital' => 0, 'status' => $status, 'estate' => 16, 'name' => ucfirst('San Pedro de Coche')];
        $data[325] = ['capital' => 0, 'status' => $status, 'estate' => 16, 'name' => ucfirst('Santa Ana de Nueva Esparta')];
        $data[326] = ['capital' => 0, 'status' => $status, 'estate' => 16, 'name' => ucfirst('Villa Rosa')];

        $data[327] = ['capital' => 0, 'status' => $status, 'estate' => 17, 'name' => ucfirst('General')];
        $data[328] = ['capital' => 0, 'status' => $status, 'estate' => 17, 'name' => ucfirst('Acarigua')];
        $data[329] = ['capital' => 0, 'status' => $status, 'estate' => 17, 'name' => ucfirst('Agua Blanca')];
        $data[330] = ['capital' => 0, 'status' => $status, 'estate' => 17, 'name' => ucfirst('Araure')];
        $data[331] = ['capital' => 0, 'status' => $status, 'estate' => 17, 'name' => ucfirst('Biscucuy')];
        $data[332] = ['capital' => 0, 'status' => $status, 'estate' => 17, 'name' => ucfirst('Boconoito')];
        $data[333] = ['capital' => 0, 'status' => $status, 'estate' => 17, 'name' => ucfirst('Campo Elias')];
        $data[334] = ['capital' => 0, 'status' => $status, 'estate' => 17, 'name' => ucfirst('Chabasquen')];
        $data[335] = ['capital' => 1, 'status' => $status, 'estate' => 17, 'name' => ucfirst('Guanare')];
        $data[336] = ['capital' => 0, 'status' => $status, 'estate' => 17, 'name' => ucfirst('Guanarito')];
        $data[337] = ['capital' => 0, 'status' => $status, 'estate' => 17, 'name' => ucfirst('La ApariciOn')];
        $data[338] = ['capital' => 0, 'status' => $status, 'estate' => 17, 'name' => ucfirst('La MisiOn')];
        $data[339] = ['capital' => 0, 'status' => $status, 'estate' => 17, 'name' => ucfirst('Mesa de Cavacas')];
        $data[340] = ['capital' => 0, 'status' => $status, 'estate' => 17, 'name' => ucfirst('Ospino')];
        $data[341] = ['capital' => 0, 'status' => $status, 'estate' => 17, 'name' => ucfirst('PapelOn')];
        $data[342] = ['capital' => 0, 'status' => $status, 'estate' => 17, 'name' => ucfirst('Payara')];
        $data[343] = ['capital' => 0, 'status' => $status, 'estate' => 17, 'name' => ucfirst('Pimpinela')];
        $data[344] = ['capital' => 0, 'status' => $status, 'estate' => 17, 'name' => ucfirst('Piritu de Portuguesa')];
        $data[345] = ['capital' => 0, 'status' => $status, 'estate' => 17, 'name' => ucfirst('San Rafael de Onoto')];
        $data[346] = ['capital' => 0, 'status' => $status, 'estate' => 17, 'name' => ucfirst('Santa Rosalia')];
        $data[347] = ['capital' => 0, 'status' => $status, 'estate' => 17, 'name' => ucfirst('Turen')];

        $data[348] = ['capital' => 0, 'status' => $status, 'estate' => 18, 'name' => ucfirst('General')];
        $data[349] = ['capital' => 0, 'status' => $status, 'estate' => 18, 'name' => ucfirst('Altos de Sucre')];
        $data[350] = ['capital' => 0, 'status' => $status, 'estate' => 18, 'name' => ucfirst('Araya')];
        $data[351] = ['capital' => 0, 'status' => $status, 'estate' => 18, 'name' => ucfirst('Cariaco')];
        $data[352] = ['capital' => 0, 'status' => $status, 'estate' => 18, 'name' => ucfirst('Carupano')];
        $data[353] = ['capital' => 0, 'status' => $status, 'estate' => 18, 'name' => ucfirst('Casanay')];
        $data[354] = ['capital' => 1, 'status' => $status, 'estate' => 18, 'name' => ucfirst('Cumana')];
        $data[355] = ['capital' => 0, 'status' => $status, 'estate' => 18, 'name' => ucfirst('Cumanacoa')];
        $data[356] = ['capital' => 0, 'status' => $status, 'estate' => 18, 'name' => ucfirst('El Morro Puerto Santo')];
        $data[357] = ['capital' => 0, 'status' => $status, 'estate' => 18, 'name' => ucfirst('El Pilar')];
        $data[358] = ['capital' => 0, 'status' => $status, 'estate' => 18, 'name' => ucfirst('El Poblado')];
        $data[359] = ['capital' => 0, 'status' => $status, 'estate' => 18, 'name' => ucfirst('Guaca')];
        $data[360] = ['capital' => 0, 'status' => $status, 'estate' => 18, 'name' => ucfirst('Guiria')];
        $data[361] = ['capital' => 0, 'status' => $status, 'estate' => 18, 'name' => ucfirst('Irapa')];
        $data[362] = ['capital' => 0, 'status' => $status, 'estate' => 18, 'name' => ucfirst('Manicuare')];
        $data[363] = ['capital' => 0, 'status' => $status, 'estate' => 18, 'name' => ucfirst('Mariguitar')];
        $data[364] = ['capital' => 0, 'status' => $status, 'estate' => 18, 'name' => ucfirst('Rio Caribe')];
        $data[365] = ['capital' => 0, 'status' => $status, 'estate' => 18, 'name' => ucfirst('San Antonio del Golfo')];
        $data[366] = ['capital' => 0, 'status' => $status, 'estate' => 18, 'name' => ucfirst('San Jose de Aerocuar')];
        $data[367] = ['capital' => 0, 'status' => $status, 'estate' => 18, 'name' => ucfirst('San Vicente de Sucre')];
        $data[368] = ['capital' => 0, 'status' => $status, 'estate' => 18, 'name' => ucfirst('Santa Fe de Sucre')];
        $data[369] = ['capital' => 0, 'status' => $status, 'estate' => 18, 'name' => ucfirst('Tunapuy')];
        $data[370] = ['capital' => 0, 'status' => $status, 'estate' => 18, 'name' => ucfirst('Yaguaraparo')];
        $data[371] = ['capital' => 0, 'status' => $status, 'estate' => 18, 'name' => ucfirst('Yoco')];

        $data[372] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('General')];
        $data[373] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('Abejales')];
        $data[374] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('Borota')];
        $data[375] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('Bramon')];
        $data[376] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('Capacho')];
        $data[377] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('ColOn')];
        $data[378] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('Coloncito')];
        $data[379] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('Cordero')];
        $data[380] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('El Cobre')];
        $data[381] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('El Pinal')];
        $data[382] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('Independencia')];
        $data[383] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('La Fria')];
        $data[384] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('La Grita')];
        $data[385] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('La Pedrera')];
        $data[386] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('La Tendida')];
        $data[387] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('Las Delicias')];
        $data[388] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('Las Hernandez')];
        $data[389] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('Lobatera')];
        $data[390] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('Michelena')];
        $data[391] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('Palmira')];
        $data[392] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('Pregonero')];
        $data[393] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('Queniquea')];
        $data[394] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('Rubio')];
        $data[395] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('San Antonio del Tachira')];
        $data[396] = ['capital' => 1, 'status' => $status, 'estate' => 19, 'name' => ucfirst('San Cristobal')];
        $data[397] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('San Jose de Bolivar')];
        $data[398] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('San Josecito')];
        $data[399] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('San Pedro del Rio')];
        $data[400] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('Santa Ana Tachira')];
        $data[401] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('Seboruco')];
        $data[402] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('Tariba')];
        $data[403] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('Umuquena')];
        $data[404] = ['capital' => 0, 'status' => $status, 'estate' => 19, 'name' => ucfirst('Urena')];

        $data[405] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('General')];
        $data[406] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('Batatal')];
        $data[407] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('Betijoque')];
        $data[408] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('BoconO')];
        $data[409] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('Carache')];
        $data[410] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('Chejende')];
        $data[411] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('Cuicas')];
        $data[412] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('El Dividive')];
        $data[413] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('El Jaguito')];
        $data[414] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('Escuque')];
        $data[415] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('Isnotu')];
        $data[416] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('JajO')];
        $data[417] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('La Ceiba')];
        $data[418] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('La ConcepciOn de Trujllo')];
        $data[419] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('La Mesa de Esnujaque')];
        $data[420] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('La Puerta')];
        $data[421] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('La Quebrada')];
        $data[422] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('Mendoza Fria')];
        $data[423] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('Meseta de Chimpire')];
        $data[424] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('Monay')];
        $data[425] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('Motatan')];
        $data[426] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('Pampan')];
        $data[427] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('Pampanito')];
        $data[428] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('Sabana de Mendoza')];
        $data[429] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('San Lazaro')];
        $data[430] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('Santa Ana de Trujillo')];
        $data[431] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('TostOs')];
        $data[432] = ['capital' => 1, 'status' => $status, 'estate' => 20, 'name' => ucfirst('Trujillo')];
        $data[433] = ['capital' => 0, 'status' => $status, 'estate' => 20, 'name' => ucfirst('Valera')];

        $data[434] = ['capital' => 0, 'status' => $status, 'estate' => 21, 'name' => ucfirst('General')];
        $data[435] = ['capital' => 0, 'status' => $status, 'estate' => 21, 'name' => ucfirst('Carayaca')];
        $data[436] = ['capital' => 0, 'status' => $status, 'estate' => 21, 'name' => ucfirst('Litoral')];
        $data[437] = ['capital' => 1, 'status' => $status, 'estate' => 21, 'name' => ucfirst('La Guaira')];
        $data[438] = ['capital' => 0, 'status' => $status, 'estate' => 21, 'name' => ucfirst('Catia La Mar')];
        $data[439] = ['capital' => 0, 'status' => $status, 'estate' => 21, 'name' => ucfirst('Macuto')];
        $data[440] = ['capital' => 0, 'status' => $status, 'estate' => 21, 'name' => ucfirst('Naiguata')];
        
        $data[441] = ['capital' => 1, 'status' => $status, 'estate' => 22, 'name' => ucfirst('General')];
        $data[442] = ['capital' => 1, 'status' => $status, 'estate' => 22, 'name' => ucfirst('San Felipe')];
        $data[443] = ['capital' => 0, 'status' => $status, 'estate' => 22, 'name' => ucfirst('Boraure')];
        $data[444] = ['capital' => 0, 'status' => $status, 'estate' => 22, 'name' => ucfirst('Campo Elias de Yaracuy')];
        $data[445] = ['capital' => 0, 'status' => $status, 'estate' => 22, 'name' => ucfirst('Chivacoa')];
        $data[446] = ['capital' => 0, 'status' => $status, 'estate' => 22, 'name' => ucfirst('Cocorote')];
        $data[447] = ['capital' => 0, 'status' => $status, 'estate' => 22, 'name' => ucfirst('Farriar')];
        $data[448] = ['capital' => 0, 'status' => $status, 'estate' => 22, 'name' => ucfirst('Guama')];
        $data[448] = ['capital' => 0, 'status' => $status, 'estate' => 22, 'name' => ucfirst('Marin')];
        $data[450] = ['capital' => 0, 'status' => $status, 'estate' => 22, 'name' => ucfirst('Nirgua')];
        $data[451] = ['capital' => 0, 'status' => $status, 'estate' => 22, 'name' => ucfirst('Sabana de Parra')];
        $data[452] = ['capital' => 0, 'status' => $status, 'estate' => 22, 'name' => ucfirst('Salom')];
        $data[453] = ['capital' => 0, 'status' => $status, 'estate' => 22, 'name' => ucfirst('Aroa')];
        $data[454] = ['capital' => 0, 'status' => $status, 'estate' => 22, 'name' => ucfirst('San Pablo de Yaracuy')];
        $data[455] = ['capital' => 0, 'status' => $status, 'estate' => 22, 'name' => ucfirst('Urachiche')];
        $data[456] = ['capital' => 0, 'status' => $status, 'estate' => 22, 'name' => ucfirst('Yaritagua')];
        $data[457] = ['capital' => 0, 'status' => $status, 'estate' => 22, 'name' => ucfirst('Yumare')];

        $data[458] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('General')];
        $data[459] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Bachaquero')];
        $data[460] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Bobures')];
        $data[461] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Cabimas')];
        $data[462] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Campo ConcepciOn')];
        $data[463] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Campo Mara')];
        $data[464] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Campo Rojo')];
        $data[465] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Carrasquero')];
        $data[466] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Casigua')];
        $data[467] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Chiquinquira')];
        $data[468] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Ciudad Ojeda')];
        $data[469] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('El Batey')];
        $data[470] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('El Carmelo')];
        $data[471] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('El Chivo')];
        $data[472] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('El Guayabo')];
        $data[473] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('El Mene')];
        $data[474] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('El Venado')];
        $data[475] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Encontrados')];
        $data[476] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Gibraltar')];
        $data[477] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Isla de Toas')];
        $data[478] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('La ConcepciOn del Zulia')];
        $data[479] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('La Paz')];
        $data[480] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('La Sierrita')];
        $data[481] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Lagunillas del Zulia')];
        $data[482] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Las Piedras de Perija')];
        $data[483] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Los Cortijos')];
        $data[484] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Machiques')];
        $data[485] = ['capital' => 1, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Maracaibo')];
        $data[486] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Mene Grande')];
        $data[487] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Palmarejo')];
        $data[488] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Paraguaipoa')];
        $data[489] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Potrerito')];
        $data[490] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Pueblo Nuevo del Zulia')];
        $data[491] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Puertos de Altagracia')];
        $data[492] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Punta Gorda')];
        $data[493] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Sabaneta de Palma')];
        $data[494] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('San Francisco')];
        $data[495] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('San Jose de Perija')];
        $data[496] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('San Rafael del Mojan')];
        $data[497] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('San Timoteo')];
        $data[498] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Santa Barbara Del Zulia')];
        $data[499] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Santa Cruz de Mara')];
        $data[500] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Santa Cruz del Zulia')];
        $data[501] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Santa Rita')];
        $data[502] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Sinamaica')];
        $data[503] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Tamare')];
        $data[504] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Tia Juana')];
        $data[505] = ['capital' => 0, 'status' => $status, 'estate' => 23, 'name' => ucfirst('Villa del Rosario')];

        $data[506] = ['capital' => 0, 'status' => $status, 'estate' => 24, 'name' => ucfirst('General')];
        $data[507] = ['capital' => 1, 'status' => $status, 'estate' => 24, 'name' => ucfirst('Caracas')];
        $data[508] = ['capital' => 0, 'status' => $status, 'estate' => 24, 'name' => ucfirst('El Junquito')];

        $data[509] = ['capital' => 0, 'status' => $status, 'estate' => 25, 'name' => ucfirst('General')];
        $data[510] = ['capital' => 0, 'status' => $status, 'estate' => 25, 'name' => ucfirst('Archipielago Los Roques')];
        $data[511] = ['capital' => 0, 'status' => $status, 'estate' => 25, 'name' => ucfirst('Archipielago Los Monjes')];
        $data[512] = ['capital' => 0, 'status' => $status, 'estate' => 25, 'name' => ucfirst('Isla La Tortuga y Cayos adyacentes')];
        $data[513] = ['capital' => 0, 'status' => $status, 'estate' => 25, 'name' => ucfirst('Isla La Sola')];
        $data[514] = ['capital' => 0, 'status' => $status, 'estate' => 25, 'name' => ucfirst('Islas Los Testigos')];
        $data[515] = ['capital' => 0, 'status' => $status, 'estate' => 25, 'name' => ucfirst('Islas Los Frailes')];
        $data[516] = ['capital' => 0, 'status' => $status, 'estate' => 25, 'name' => ucfirst('Isla La Orchila')];
        $data[517] = ['capital' => 0, 'status' => $status, 'estate' => 25, 'name' => ucfirst('Archipielago Las Aves')];
        $data[518] = ['capital' => 0, 'status' => $status, 'estate' => 25, 'name' => ucfirst('Isla de Aves')];
        $data[519] = ['capital' => 0, 'status' => $status, 'estate' => 25, 'name' => ucfirst('Isla La Blanquilla')];
        $data[520] = ['capital' => 0, 'status' => $status, 'estate' => 25, 'name' => ucfirst('Isla de Patos')];
        $data[521] = ['capital' => 0, 'status' => $status, 'estate' => 25, 'name' => ucfirst('Islas Los Hermanos')];

        foreach ($data as $d => $da) 
        {
            $new    =   New City();
            $new->name          =   $da['name'];
            $new->capital       =   $da['capital'];
            $new->estate_id     =   $da['estate'];
            $new->status_id     =   $da['status'];
            
            try {
                $new->save();
            } catch (\Exception $e) {
                var_dump($e->getMessage());
            }
        }
    }
}
